import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

export async function POST() {
  try {
    const existingCategories = await db.category.count()
    if (existingCategories > 0) {
      return NextResponse.json({ message: 'Seed data already exists' }, { status: 200 })
    }

    // Create categories
    const religious = await db.category.create({
      data: { nameBadini: 'ئایینی', nameSorani: 'ئایینی' },
    })
    const science = await db.category.create({
      data: { nameBadini: 'زانستی', nameSorani: 'زانستی' },
    })
    const history = await db.category.create({
      data: { nameBadini: 'مێژوویی', nameSorani: 'مێژوویی' },
    })
    const geography = await db.category.create({
      data: { nameBadini: 'جوگرافی', nameSorani: 'جوگرافی' },
    })
    const sports = await db.category.create({
      data: { nameBadini: 'وەرزشی', nameSorani: 'وەرزشی' },
    })
    const general = await db.category.create({
      data: { nameBadini: 'گشتی', nameSorani: 'گشتی' },
    })

    // ===================== Religious Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'چەند ڕوکوعەکان ل نێژا ئێوارێدا هەن؟',
          textSorani: 'چەند ڕکوعەت ل نوێژى ئێوارادا هەیە؟',
          option1Badini: '٣', option1Sorani: '٣',
          option2Badini: '٤', option2Sorani: '٤',
          option3Badini: '٢', option3Sorani: '٢',
          option4Badini: '٥', option4Sorani: '٥',
          correctAnswer: 2,
          categoryId: religious.id,
        },
        {
          textBadini: 'پێغەمبەری ئیسلام کێیە؟',
          textSorani: 'پێغەمبەری ئیسلام کێیە؟',
          option1Badini: 'حەزرەتی عیسا', option1Sorani: 'حەزرەتى عیسا',
          option2Badini: 'حەزرەتی مووسا', option2Sorani: 'حەزرەتى مووسا',
          option3Badini: 'حەزرەتی محەمەد ﷺ', option3Sorani: 'حەزرەتى محەمەد ﷺ',
          option4Badini: 'حەزرەتی ئیبراھیم', option4Sorani: 'حەزرەتى ئیبراھیم',
          correctAnswer: 3,
          categoryId: religious.id,
        },
        {
          textBadini: 'کام سورەتا قورئانێ د هەر نێژایەکدا دخوێنیت؟',
          textSorani: 'کام سورەتى قورئان ل هەر نوێژێکدا دەخوێنیت؟',
          option1Badini: 'سورەتی بەقەرە', option1Sorani: 'سورەتى بەقەرە',
          option2Badini: 'سورەتی فاتیحە', option2Sorani: 'سورەتى فاتیحە',
          option3Badini: 'سورەتی ئیخلاس', option3Sorani: 'سورەتى ئیخلاس',
          option4Badini: 'سورەتی ناس', option4Sorani: 'سورەتى ناس',
          correctAnswer: 2,
          categoryId: religious.id,
        },
        {
          textBadini: 'ژ چەند ئایەتان قورئان پێکدێت؟',
          textSorani: 'ل چەند ئایەتان قورئان پێکدێت؟',
          option1Badini: '٦٢٣٦', option1Sorani: '٦٢٣٦',
          option2Badini: '٦٦٦٦', option2Sorani: '٦٦٦٦',
          option3Badini: '٦٠٠٠', option3Sorani: '٦٠٠٠',
          option4Badini: '٧٠٠٠', option4Sorani: '٧٠٠٠',
          correctAnswer: 1,
          categoryId: religious.id,
        },
        {
          textBadini: 'حەج ل کام مانگێدا ئەنجام ددرێت؟',
          textSorani: 'حەج ل کام مانگێدا ئەنجام دەدرێت؟',
          option1Badini: 'ڕەمەزان', option1Sorani: 'ڕەمەزان',
          option2Badini: 'زولحەججە', option2Sorani: 'زولحەججە',
          option3Badini: 'شەووال', option3Sorani: 'شەووال',
          option4Badini: 'موعەڕەم', option4Sorani: 'موعەڕەم',
          correctAnswer: 2,
          categoryId: religious.id,
        },
        {
          textBadini: 'چەند ڕوکوعەکان ل نێژا بەیانیدا هەن؟',
          textSorani: 'چەند ڕکوعەت ل نوێژى بەیانیدا هەیە؟',
          option1Badini: '٢', option1Sorani: '٢',
          option2Badini: '٣', option2Sorani: '٣',
          option3Badini: '٤', option3Sorani: '٤',
          option4Badini: '١', option4Sorani: '١',
          correctAnswer: 1,
          categoryId: religious.id,
        },
        {
          textBadini: 'نێژا عیشا چەند ڕوکوعەکان هەن؟',
          textSorani: 'نوێژى عیشا چەند ڕکوعەت هەیە؟',
          option1Badini: '٣', option1Sorani: '٣',
          option2Badini: '٤', option2Sorani: '٤',
          option3Badini: '٢', option3Sorani: '٢',
          option4Badini: '٥', option4Sorani: '٥',
          correctAnswer: 2,
          categoryId: religious.id,
        },
        {
          textBadini: 'کام پێغەمبەر ب شەڕا دریا دبڕیەوە؟',
          textSorani: 'کام پێغەمبەر ب شەڕى دریا دەبڕیەوە؟',
          option1Badini: 'حەزرەتی نوح', option1Sorani: 'حەزرەتى نوح',
          option2Badini: 'حەزرەتی مووسا', option2Sorani: 'حەزرەتى مووسا',
          option3Badini: 'حەزرەتی عیسا', option3Sorani: 'حەزرەتى عیسا',
          option4Badini: 'حەزرەتی یونس', option4Sorani: 'حەزرەتى یونس',
          correctAnswer: 2,
          categoryId: religious.id,
        },
        {
          textBadini: 'کام سورەتا قورئانێ هەرە درێژە؟',
          textSorani: 'کام سورەتى قورئان هەرە درێژە؟',
          option1Badini: 'سورەتی ئالی عیمران', option1Sorani: 'سورەتى ئالى عیمران',
          option2Badini: 'سورەتی نیسا', option2Sorani: 'سورەتى نیسا',
          option3Badini: 'سورەتی بەقەرە', option3Sorani: 'سورەتى بەقەرە',
          option4Badini: 'سورەتی مائیدە', option4Sorani: 'سورەتى مائیدە',
          correctAnswer: 3,
          categoryId: religious.id,
        },
        {
          textBadini: 'ڕۆژا عەرەفە ل کام ڕۆژا حەجێدایە؟',
          textSorani: 'ڕۆژى عەرەفە ل کام ڕۆژى حەجێدایە؟',
          option1Badini: '٨ زولحەججە', option1Sorani: '٨ زولحەججە',
          option2Badini: '٩ زولحەججە', option2Sorani: '٩ زولحەججە',
          option3Badini: '١٠ زولحەججە', option3Sorani: '١٠ زولحەججە',
          option4Badini: '٧ زولحەججە', option4Sorani: '٧ زولحەججە',
          correctAnswer: 2,
          categoryId: religious.id,
        },
      ],
    })

    // ===================== Science Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'زەوی چەند ساڵانە خۆی دگەڕێنێتەڤە ل دوری خۆرێ؟',
          textSorani: 'زەوى چەند ساڵانە خۆى دەگەڕێنێتەوە لە دەورى خۆر؟',
          option1Badini: '٣٦٥ ڕۆژ', option1Sorani: '٣٦٥ ڕۆژ',
          option2Badini: '٣٠٠ ڕۆژ', option2Sorani: '٣٠٠ ڕۆژ',
          option3Badini: '٤٠٠ ڕۆژ', option3Sorani: '٤٠٠ ڕۆژ',
          option4Badini: '٢٥٠ ڕۆژ', option4Sorani: '٢٥٠ ڕۆژ',
          correctAnswer: 1,
          categoryId: science.id,
        },
        {
          textBadini: 'ئاویان H2O پێکدێت ژ چەند ئەتۆمان؟',
          textSorani: 'ئاوى H2O پێکدێت ل چەند ئەتۆم؟',
          option1Badini: '٢ هیدروجین و ١ ئۆکسجین', option1Sorani: '٢ هیدروجین و ١ ئۆکسجین',
          option2Badini: '١ هیدروجین و ٢ ئۆکسجین', option2Sorani: '١ هیدروجین و ٢ ئۆکسجین',
          option3Badini: '٣ هیدروجین و ١ ئۆکسجین', option3Sorani: '٣ هیدروجین و ١ ئۆکسجین',
          option4Badini: '٢ هیدروجین و ٢ ئۆکسجین', option4Sorani: '٢ هیدروجین و ٢ ئۆکسجین',
          correctAnswer: 1,
          categoryId: science.id,
        },
        {
          textBadini: 'خێراترین شت ل جیهانێدا چییە؟',
          textSorani: 'خێراترین شت ل جیهاندا چییە؟',
          option1Badini: 'دەنگ', option1Sorani: 'دەنگ',
          option2Badini: 'ڕووناکی', option2Sorani: 'ڕووناکی',
          option3Badini: 'ئاو', option3Sorani: 'ئاو',
          option4Badini: 'با', option4Sorani: 'با',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'هەسارەی زەوی چەندەمین هەسارەیە ژ خۆرێ؟',
          textSorani: 'هەسارەى زەوى چەندەمین هەسارەیە ل خۆر؟',
          option1Badini: 'سێیەم', option1Sorani: 'سێیەم',
          option2Badini: 'دوویەم', option2Sorani: 'دوویەم',
          option3Badini: 'چوارەم', option3Sorani: 'چوارەم',
          option4Badini: 'پێنجەم', option4Sorani: 'پێنجەم',
          correctAnswer: 1,
          categoryId: science.id,
        },
        {
          textBadini: 'کام گازی هەوای زەوی پێکدێنیت هەرە زۆرە؟',
          textSorani: 'کام گازى هەوای زەوى پێکدێنیت هەرە زۆرە؟',
          option1Badini: 'ئۆکسجین', option1Sorani: 'ئۆکسجین',
          option2Badini: 'نایترۆجین', option2Sorani: 'نایترۆجین',
          option3Badini: 'کاربۆن دای ئۆکساید', option3Sorani: 'کاربۆن دای ئۆکساید',
          option4Badini: 'هیدروجین', option4Sorani: 'هیدروجین',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'مێشکا مرۆڤی چەند کیلۆگرامە؟',
          textSorani: 'مێشکى مرۆڤ چەند کیلۆگرامە؟',
          option1Badini: 'نزیک ١ کگم', option1Sorani: 'نزیک ١ کگم',
          option2Badini: 'نزیک ١.٥ کگم', option2Sorani: 'نزیک ١.٥ کگم',
          option3Badini: 'نزیک ٢ کگم', option3Sorani: 'نزیک ٢ کگم',
          option4Badini: 'نزیک ٣ کگم', option4Sorani: 'نزیک ٣ کگم',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'کام ئۆرگان لەشێ مرۆڤی هەرە گەورەیە؟',
          textSorani: 'کام ئۆرگانى لەشى مرۆڤ هەرە گەورەیە؟',
          option1Badini: 'دڵ', option1Sorani: 'دڵ',
          option2Badini: 'جگەر', option2Sorani: 'جگەر',
          option3Badini: 'سییەکان', option3Sorani: 'سییەکان',
          option4Badini: 'گورچیلە', option4Sorani: 'گورچیلە',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'خۆر چەند هەسارەیەکی هەیە؟',
          textSorani: 'خۆر چەند هەسارەیەکى هەیە؟',
          option1Badini: '٧', option1Sorani: '٧',
          option2Badini: '٨', option2Sorani: '٨',
          option3Badini: '٩', option3Sorani: '٩',
          option4Badini: '١٠', option4Sorani: '١٠',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'چەند ئێسک لەشێ مرۆڤی پێگەیشتودا هەن؟',
          textSorani: 'چەند ئێسک لەشى مرۆڤى پێگەیشتودا هەن؟',
          option1Badini: '١٨٦', option1Sorani: '١٨٦',
          option2Badini: '٢٠٦', option2Sorani: '٢٠٦',
          option3Badini: '٣٠٦', option3Sorani: '٣٠٦',
          option4Badini: '١٠٦', option4Sorani: '١٠٦',
          correctAnswer: 2,
          categoryId: science.id,
        },
        {
          textBadini: 'کام هەسارە هەرە نزیکە ژ خۆرێ؟',
          textSorani: 'کام هەسارە هەرە نزیکە ل خۆر؟',
          option1Badini: 'ڤێنوس', option1Sorani: 'ڤێنوس',
          option2Badini: 'مەریخ', option2Sorani: 'مەریخ',
          option3Badini: 'عاتارد', option3Sorani: 'عاتارد',
          option4Badini: 'زەوی', option4Sorani: 'زەوی',
          correctAnswer: 3,
          categoryId: science.id,
        },
      ],
    })

    // ===================== History Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'صلاحەدینی ئەیوبی ل کام شارێدا لەدایک بوو؟',
          textSorani: 'صلاحەدینی ئەیوبی ل کام شارێدا لەدایک بوو؟',
          option1Badini: 'تکریت', option1Sorani: 'تکریت',
          option2Badini: 'دیمەشق', option2Sorani: 'دیمەشق',
          option3Badini: 'قاهیرە', option3Sorani: 'قاهیرە',
          option4Badini: 'بەغدا', option4Sorani: 'بەغدا',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'جەنگی جیهانی یەکەم ل کام ساڵێدا دەستی پێکرد؟',
          textSorani: 'جەنگى جیهانى یەکەم ل کام ساڵێدا دەستى پێکرد؟',
          option1Badini: '١٩١٤', option1Sorani: '١٩١٤',
          option2Badini: '١٩١٨', option2Sorani: '١٩١٨',
          option3Badini: '١٩٣٩', option3Sorani: '١٩٣٩',
          option4Badini: '١٩٠٥', option4Sorani: '١٩٠٥',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'کام شارێ پایتەختی ئیمپراتۆرییەتی عوسمانی بوو؟',
          textSorani: 'کام شار پایتەختی ئیمپراتۆرییەتی عوسمانی بوو؟',
          option1Badini: 'ئەنقەرە', option1Sorani: 'ئەنقەرە',
          option2Badini: 'ئەستەمبوڵ', option2Sorani: 'ئەستەمبوڵ',
          option3Badini: 'ئیزمیر', option3Sorani: 'ئیزمیر',
          option4Badini: 'بورسا', option4Sorani: 'بورسا',
          correctAnswer: 2,
          categoryId: history.id,
        },
        {
          textBadini: 'کام ئیمپراتۆرییەت هەرە گەورەترین بوو ل مێژوویدا؟',
          textSorani: 'کام ئیمپراتۆرییەت هەرە گەورەترین بوو ل مێژوودا؟',
          option1Badini: 'ئیمپراتۆرییەتی ڕۆمانی', option1Sorani: 'ئیمپراتۆرییەتی ڕۆمانی',
          option2Badini: 'ئیمپراتۆرییەتی بریتانی', option2Sorani: 'ئیمپراتۆرییەتی بریتانی',
          option3Badini: 'ئیمپراتۆرییەتی مەغۆل', option3Sorani: 'ئیمپراتۆرییەتی مەغۆل',
          option4Badini: 'ئیمپراتۆرییەتی عوسمانی', option4Sorani: 'ئیمپراتۆرییەتی عوسمانی',
          correctAnswer: 2,
          categoryId: history.id,
        },
        {
          textBadini: 'کوردستانی باشوور ل کام ساڵێدا بەڕێوەبەرایەتی خۆی وەرگرت؟',
          textSorani: 'کوردستانی باشوور ل کام ساڵێدا بەڕێوەبەرایەتى خۆى وەرگرت؟',
          option1Badini: '١٩٩١', option1Sorani: '١٩٩١',
          option2Badini: '٢٠٠٣', option2Sorani: '٢٠٠٣',
          option3Badini: '١٩٨٨', option3Sorani: '١٩٨٨',
          option4Badini: '٢٠٠٥', option4Sorani: '٢٠٠٥',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'جەنگی جیهانی دوویەم ل کام ساڵێدا تەواو بوو؟',
          textSorani: 'جەنگى جیهانى دوویەم ل کام ساڵێدا تەواو بوو؟',
          option1Badini: '١٩٤٣', option1Sorani: '١٩٤٣',
          option2Badini: '١٩٤٤', option2Sorani: '١٩٤٤',
          option3Badini: '١٩٤٥', option3Sorani: '١٩٤٥',
          option4Badini: '١٩٤٦', option4Sorani: '١٩٤٦',
          correctAnswer: 3,
          categoryId: history.id,
        },
        {
          textBadini: 'محەمەد عەلی پاشا کێ بوو؟',
          textSorani: 'محەمەد عەلى پاشا کێ بوو؟',
          option1Badini: 'پاشایێ میسر', option1Sorani: 'پاشایێ میسر',
          option2Badini: 'پاشایێ عوسمانی', option2Sorani: 'پاشایێ عوسمانی',
          option3Badini: 'پاشایێ فارس', option3Sorani: 'پاشایێ فارس',
          option4Badini: 'پاشایێ ڕۆمان', option4Sorani: 'پاشایێ ڕۆمان',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'شەڕا حەلەب ل کام ساڵێدا بوو ک سلاحەدین سەرکەوت؟',
          textSorani: 'شەڕى حەلەب ل کام ساڵێدا بوو ک صلاحەدین سەرکەوت؟',
          option1Badini: '١١٨٧', option1Sorani: '١١٨٧',
          option2Badini: '١١٩٠', option2Sorani: '١١٩٠',
          option3Badini: '١١٧٥', option3Sorani: '١١٧٥',
          option4Badini: '١٢٠٠', option4Sorani: '١٢٠٠',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'بابلۆنی کۆن ل کام وڵاتێ ئێستادا بوو؟',
          textSorani: 'بابلۆنى کۆن ل کام وڵاتێ ئێستادا بوو؟',
          option1Badini: 'عێراق', option1Sorani: 'عێراق',
          option2Badini: 'ئێران', option2Sorani: 'ئێران',
          option3Badini: 'تورکیا', option3Sorani: 'تورکیا',
          option4Badini: 'میسر', option4Sorani: 'میصر',
          correctAnswer: 1,
          categoryId: history.id,
        },
        {
          textBadini: 'کام شارێ هەرە کۆنە ل جیهانێدا ک هێشتا مەبەستە؟',
          textSorani: 'کام شار هەرە کۆنە ل جیهاندا ک هێشتا مەبەستە؟',
          option1Badini: 'دیمەشق', option1Sorani: 'دیمەشق',
          option2Badini: 'قاهیرە', option2Sorani: 'قاهیرە',
          option3Badini: 'ئەستەمبوڵ', option3Sorani: 'ئەستەمبوڵ',
          option4Badini: 'بەغدا', option4Sorani: 'بەغدا',
          correctAnswer: 1,
          categoryId: history.id,
        },
      ],
    })

    // ===================== Geography Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'کام وڵات گەورەترینە ل جیهانێدا ب ڕووبەرێ؟',
          textSorani: 'کام وڵات گەورەترینە ل جیهاندا ب ڕووبەر؟',
          option1Badini: 'چین', option1Sorani: 'چین',
          option2Badini: 'کەنەدا', option2Sorani: 'کەنەدا',
          option3Badini: 'ڕووسیا', option3Sorani: 'ڕووسیا',
          option4Badini: 'ئەمریکا', option4Sorani: 'ئەمریکا',
          correctAnswer: 3,
          categoryId: geography.id,
        },
        {
          textBadini: 'کام چیا بەرزترینە ل جیهانێدا؟',
          textSorani: 'کام چیا بەرزترینە ل جیهاندا؟',
          option1Badini: 'ک٢', option1Sorani: 'ک٢',
          option2Badini: 'ئێڤرست', option2Sorani: 'ئێڤرست',
          option3Badini: 'کانچنجونگا', option3Sorani: 'کانچنجونگا',
          option4Badini: 'ماکالو', option4Sorani: 'ماکالو',
          correctAnswer: 2,
          categoryId: geography.id,
        },
        {
          textBadini: 'ڕووباری نیل ل کام وڵاتێدا دەست پێ دکەت؟',
          textSorani: 'ڕووبارى نیل ل کام وڵاتێدا دەست پێ دەکات؟',
          option1Badini: 'میصر', option1Sorani: 'میصر',
          option2Badini: 'سوودان', option2Sorani: 'سوودان',
          option3Badini: 'ئەسیوپیا', option3Sorani: 'ئەسیوپیا',
          option4Badini: 'یوگەندا', option4Sorani: 'یوگەندا',
          correctAnswer: 3,
          categoryId: geography.id,
        },
        {
          textBadini: 'پایتەختی تورکیا کام شارە؟',
          textSorani: 'پایتەختی تورکیا کام شارە؟',
          option1Badini: 'ئەستەمبوڵ', option1Sorani: 'ئەستەمبوڵ',
          option2Badini: 'ئەنقەرە', option2Sorani: 'ئەنقەرە',
          option3Badini: 'ئیزمیر', option3Sorani: 'ئیزمیر',
          option4Badini: 'ئەنتالیا', option4Sorani: 'ئەنتالیا',
          correctAnswer: 2,
          categoryId: geography.id,
        },
        {
          textBadini: 'ڕووباری دیجلە ل کام وڵاتێدا دەست پێ دکەت؟',
          textSorani: 'ڕووبارى دیجلە ل کام وڵاتێدا دەست پێ دەکات؟',
          option1Badini: 'عێراق', option1Sorani: 'عێراق',
          option2Badini: 'تورکیا', option2Sorani: 'تورکیا',
          option3Badini: 'سووریا', option3Sorani: 'سووریا',
          option4Badini: 'ئێران', option4Sorani: 'ئێران',
          correctAnswer: 2,
          categoryId: geography.id,
        },
        {
          textBadini: 'کام وڵات هەرە زۆر ژەهەردارە ل جیهانێدا؟',
          textSorani: 'کام وڵات هەرە زۆر دانیشتووى هەیە ل جیهاندا؟',
          option1Badini: 'هیندستان', option1Sorani: 'هیندستان',
          option2Badini: 'چین', option2Sorani: 'چین',
          option3Badini: 'ئەمریکا', option3Sorani: 'ئەمریکا',
          option4Badini: 'ئیندۆنیزیا', option4Sorani: 'ئیندۆنیزیا',
          correctAnswer: 2,
          categoryId: geography.id,
        },
        {
          textBadini: 'کام دەریا هەرە گەورەیە ل جیهانێدا؟',
          textSorani: 'کام دەریا هەرە گەورەیە ل جیهاندا؟',
          option1Badini: 'دەریای سپی ناوەڕاست', option1Sorani: 'دەریای سپی ناوەڕاست',
          option2Badini: 'دەریای کاسپیەن', option2Sorani: 'دەریای کاسپیەن',
          option3Badini: 'زەریای هێمن', option3Sorani: 'زەریای هێمن',
          option4Badini: 'زەریای ئەتڵەسی', option4Sorani: 'زەریای ئەتڵەسی',
          correctAnswer: 3,
          categoryId: geography.id,
        },
        {
          textBadini: 'چیای زاگرۆس ل کام وڵاتێدایە؟',
          textSorani: 'چیاى زاگرۆس ل کام وڵاتێدایە؟',
          option1Badini: 'عێراق و ئێران', option1Sorani: 'عێراق و ئێران',
          option2Badini: 'تورکیا و سوریا', option2Sorani: 'تورکیا و سوریا',
          option3Badini: 'ئێران و پاکستان', option3Sorani: 'ئێران و پاکستان',
          option4Badini: 'عێراق و تورکیا', option4Sorani: 'عێراق و تورکیا',
          correctAnswer: 1,
          categoryId: geography.id,
        },
        {
          textBadini: 'پایتەختی ئێران کام شارە؟',
          textSorani: 'پایتەختی ئێران کام شارە؟',
          option1Badini: 'ئەسفەهان', option1Sorani: 'ئەسفەهان',
          option2Badini: 'تاران', option2Sorani: 'تاران',
          option3Badini: 'شیراز', option3Sorani: 'شیراز',
          option4Badini: 'مەشھەد', option4Sorani: 'مەشھەد',
          correctAnswer: 2,
          categoryId: geography.id,
        },
        {
          textBadini: 'کام وڵات هەرە بچووکە ل جیهانێدا؟',
          textSorani: 'کام وڵات هەرە بچووکە ل جیهاندا؟',
          option1Badini: 'مۆناکۆ', option1Sorani: 'مۆناکۆ',
          option2Badini: 'ڤاتیکان', option2Sorani: 'ڤاتیکان',
          option3Badini: 'سان مارینۆ', option3Sorani: 'سان مارینۆ',
          option4Badini: 'لیختنشتاین', option4Sorani: 'لیختنشتاین',
          correctAnswer: 2,
          categoryId: geography.id,
        },
      ],
    })

    // ===================== Sports Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'کام وەرزشێ هەرە بەناوبانگە ل جیهانێدا؟',
          textSorani: 'کام وەرزش هەرە بەناوبانگە ل جیهاندا؟',
          option1Badini: 'باسکە', option1Sorani: 'باسکە',
          option2Badini: 'تۆپی پێ', option2Sorani: 'تۆپى پێ',
          option3Badini: 'تێنس', option3Sorani: 'تێنس',
          option4Badini: 'کرکێت', option4Sorani: 'کرکێت',
          correctAnswer: 2,
          categoryId: sports.id,
        },
        {
          textBadini: 'جامی جیهانی تۆپی پێ چەند ساڵانەکێ ئەنجام ددرێت؟',
          textSorani: 'جامى جیهانى تۆپى پێ چەند ساڵانە ئەنجام دەدرێت؟',
          option1Badini: '٢ ساڵ', option1Sorani: '٢ ساڵ',
          option2Badini: '٣ ساڵ', option2Sorani: '٣ ساڵ',
          option3Badini: '٤ ساڵ', option3Sorani: '٤ ساڵ',
          option4Badini: '٥ ساڵ', option4Sorani: '٥ ساڵ',
          correctAnswer: 3,
          categoryId: sports.id,
        },
        {
          textBadini: 'یاری تۆپی پێ چەند یاریزانێ لەسەر یاریگا هەن؟',
          textSorani: 'یارى تۆپى پێ چەند یاریزانێ لەسەر یاریگا هەن؟',
          option1Badini: '٩', option1Sorani: '٩',
          option2Badini: '١٠', option2Sorani: '١٠',
          option3Badini: '١١', option3Sorani: '١١',
          option4Badini: '١٢', option4Sorani: '١٢',
          correctAnswer: 3,
          categoryId: sports.id,
        },
        {
          textBadini: 'یاریا باسکە چەند یاریزانێ دخوازیت؟',
          textSorani: 'یارى باسکە چەند یاریزانێ دەخوازیت؟',
          option1Badini: '٤', option1Sorani: '٤',
          option2Badini: '٥', option2Sorani: '٥',
          option3Badini: '٦', option3Sorani: '٦',
          option4Badini: '٧', option4Sorani: '٧',
          correctAnswer: 2,
          categoryId: sports.id,
        },
        {
          textBadini: 'یاریا تێنس ل کام وڵاتێدا هەڵکەوتووە؟',
          textSorani: 'یارى تێنس ل کام وڵاتێدا هەڵکەوتووە؟',
          option1Badini: 'فەرەنسا', option1Sorani: 'فەرەنسا',
          option2Badini: 'ئینگلتەرا', option2Sorani: 'ئینگلتەرا',
          option3Badini: 'ئەمریکا', option3Sorani: 'ئەمریکا',
          option4Badini: 'ئوسترالیا', option4Sorani: 'ئوسترالیا',
          correctAnswer: 2,
          categoryId: sports.id,
        },
        {
          textBadini: 'ئۆڵۆمپیاد چەند ساڵانەکێ ئەنجام ددرێت؟',
          textSorani: 'ئۆڵۆمپیاد چەند ساڵانە ئەنجام دەدرێت؟',
          option1Badini: '٢ ساڵ', option1Sorani: '٢ ساڵ',
          option2Badini: '٣ ساڵ', option2Sorani: '٣ ساڵ',
          option3Badini: '٤ ساڵ', option3Sorani: '٤ ساڵ',
          option4Badini: '٥ ساڵ', option4Sorani: '٥ ساڵ',
          correctAnswer: 3,
          categoryId: sports.id,
        },
        {
          textBadini: 'کام وڵات زۆرترین جامی جیهانی تۆپی پێ بردوویەتی؟',
          textSorani: 'کام وڵات زۆرترین جامى جیهانى تۆپى پێ بردوویەتی؟',
          option1Badini: 'ئەڵمانیا', option1Sorani: 'ئەڵمانیا',
          option2Badini: 'ئەرژەنتین', option2Sorani: 'ئەرژەنتین',
          option3Badini: 'بەڕازیل', option3Sorani: 'بەڕازیل',
          option4Badini: 'ئیتالیا', option4Sorani: 'ئیتالیا',
          correctAnswer: 3,
          categoryId: sports.id,
        },
        {
          textBadini: 'کام یاریزانێ تۆپی پێ هەرە بەناوبانگ بوو ل مێژوویدا؟',
          textSorani: 'کام یاریزانێ تۆپى پێ هەرە بەناوبانگ بوو ل مێژوودا؟',
          option1Badini: 'کریستیانۆ ڕۆناڵدۆ', option1Sorani: 'کریستیانۆ ڕۆناڵدۆ',
          option2Badini: 'لیۆنێل مێسی', option2Sorani: 'لیۆنێل مێسی',
          option3Badini: 'پێلێ', option3Sorani: 'پێلێ',
          option4Badini: 'مارادۆنا', option4Sorani: 'مارادۆنا',
          correctAnswer: 3,
          categoryId: sports.id,
        },
        {
          textBadini: 'یاریا مەشکردن (شەڕ) ل کام وڵاتێدا هەڵکەوتووە؟',
          textSorani: 'یارى مەشکردن ل کام وڵاتێدا هەڵکەوتووە؟',
          option1Badini: 'یۆنان', option1Sorani: 'یۆنان',
          option2Badini: 'ڕۆما', option2Sorani: 'ڕۆما',
          option3Badini: 'چین', option3Sorani: 'چین',
          option4Badini: 'هیندستان', option4Sorani: 'هیندستان',
          correctAnswer: 1,
          categoryId: sports.id,
        },
        {
          textBadini: 'کام وەرزشێ ل ئۆڵۆمپیادی زستاندا هەیە؟',
          textSorani: 'کام وەرزش ل ئۆڵۆمپیادى زستاندا هەیە؟',
          option1Badini: 'سکی ئاوی', option1Sorani: 'سکى ئاوی',
          option2Badini: 'سکی بەفرین', option2Sorani: 'سکى بەفرین',
          option3Badini: 'مەلەکردن', option3Sorani: 'مەلەکردن',
          option4Badini: 'تۆپی دەستی', option4Sorani: 'تۆپى دەستى',
          correctAnswer: 2,
          categoryId: sports.id,
        },
      ],
    })

    // ===================== General Questions (10) =====================
    await db.question.createMany({
      data: [
        {
          textBadini: 'چەند ڕۆژ ل ساڵەکێدا هەن؟',
          textSorani: 'چەند ڕۆژ ل ساڵێکدا هەن؟',
          option1Badini: '٣٦٥', option1Sorani: '٣٦٥',
          option2Badini: '٣٦٠', option2Sorani: '٣٦٠',
          option3Badini: '٣٧٠', option3Sorani: '٣٧٠',
          option4Badini: '٣٥٠', option4Sorani: '٣٥٠',
          correctAnswer: 1,
          categoryId: general.id,
        },
        {
          textBadini: 'کام زمان هەرە زۆر دئاخڤرێت ل جیهانێدا؟',
          textSorani: 'کام زمان هەرە زۆر دەئاخڤرێت ل جیهاندا؟',
          option1Badini: 'ئینگلیزی', option1Sorani: 'ئینگلیزی',
          option2Badini: 'چینی ماندارین', option2Sorani: 'چینی ماندارین',
          option3Badini: 'ئیسپانی', option3Sorani: 'ئیسپانی',
          option4Badini: 'عەرەبی', option4Sorani: 'عەرەبی',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'ژ چەند وڵاتان جیهان پێکدێت؟',
          textSorani: 'ل چەند وڵاتان جیهان پێکدێت؟',
          option1Badini: 'نزیک ١٥٠', option1Sorani: 'نزیک ١٥٠',
          option2Badini: 'نزیک ١٩٥', option2Sorani: 'نزیک ١٩٥',
          option3Badini: 'نزیک ٢٠٠', option3Sorani: 'نزیک ٢٠٠',
          option4Badini: 'نزیک ١٨٠', option4Sorani: 'نزیک ١٨٠',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'دراوی ئەمریکا چی پێکدێژیت؟',
          textSorani: 'دراوى ئەمریکا چی پێکدێژیت؟',
          option1Badini: 'یۆرۆ', option1Sorani: 'یۆرۆ',
          option2Badini: 'پاوەند', option2Sorani: 'پاوەند',
          option3Badini: 'دۆلار', option3Sorani: 'دۆلار',
          option4Badini: 'فڕانک', option4Sorani: 'فڕانک',
          correctAnswer: 3,
          categoryId: general.id,
        },
        {
          textBadini: 'کام ڕۆژا هەفتەیێ یەکەمە؟',
          textSorani: 'کام ڕۆژا هەفتەیێ یەکەمە؟',
          option1Badini: 'دووشەممە', option1Sorani: 'دووشەممە',
          option2Badini: 'یەکشەممە', option2Sorani: 'یەکشەممە',
          option3Badini: 'شەممە', option3Sorani: 'شەممە',
          option4Badini: 'سێشەممە', option4Sorani: 'سێشەممە',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'کام ڕەنگا سەرەکی هەن ک لەشێ مرۆڤ دێت؟',
          textSorani: 'کام ڕەنگا سەرەکی هەن ک لەشى مرۆڤ دێت؟',
          option1Badini: '٢', option1Sorani: '٢',
          option2Badini: '٣', option2Sorani: '٣',
          option3Badini: '٤', option3Sorani: '٤',
          option4Badini: '٥', option4Sorani: '٥',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'ئەندامی نەتەوە یەکگرتووەکان ل کام شارێدایە؟',
          textSorani: 'ئەندامى نەتەوە یەکگرتووەکان ل کام شارێدایە؟',
          option1Badini: 'نیویۆرک', option1Sorani: 'نیویۆرک',
          option2Badini: 'لەندەن', option2Sorani: 'لەندەن',
          option3Badini: 'پاریس', option3Sorani: 'پاریس',
          option4Badini: 'تۆکیۆ', option4Sorani: 'تۆکیۆ',
          correctAnswer: 1,
          categoryId: general.id,
        },
        {
          textBadini: 'پیتا ئینگلیزی چەند پیتان هەن؟',
          textSorani: 'پیتا ئینگلیزی چەند پیتان هەن؟',
          option1Badini: '٢٤', option1Sorani: '٢٤',
          option2Badini: '٢٦', option2Sorani: '٢٦',
          option3Badini: '٢٨', option3Sorani: '٢٨',
          option4Badini: '٢٢', option4Sorani: '٢٢',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'کام وڵات هەرە زۆر دوورە ل هێڵی استوایی؟',
          textSorani: 'کام وڵات هەرە زۆر دانیشتووى هەیە ل ئەورووپادا؟',
          option1Badini: 'فەرەنسا', option1Sorani: 'فەرەنسا',
          option2Badini: 'ئەڵمانیا', option2Sorani: 'ئەڵمانیا',
          option3Badini: 'ڕووسیا', option3Sorani: 'ڕووسیا',
          option4Badini: 'ئیتالیا', option4Sorani: 'ئیتالیا',
          correctAnswer: 2,
          categoryId: general.id,
        },
        {
          textBadini: 'تەلەفۆنی زیرەک یەکەم جار ل کام کۆمپانیایەکێدا هەڵکەوت؟',
          textSorani: 'تەلەفۆنى زیرەک یەکەم جار ل کام کۆمپانیایەکدا هەڵکەوت؟',
          option1Badini: 'سامسۆنگ', option1Sorani: 'سامسۆنگ',
          option2Badini: 'ئەپڵ', option2Sorani: 'ئەپڵ',
          option3Badini: 'نۆکیا', option3Sorani: 'نۆکیا',
          option4Badini: 'ئێچ تی سی', option4Sorani: 'ئێچ تى سى',
          correctAnswer: 2,
          categoryId: general.id,
        },
      ],
    })

    return NextResponse.json({ message: 'Seed data created successfully' }, { status: 201 })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({ error: 'Failed to seed data' }, { status: 500 })
  }
}
